name: Charm Build
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-charm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow
      - run: sudo snap install charmcraft --channel=2.x/stable --classic
      - run: sudo charmcraft pack --destructive-mode --verbosity=trace
      - uses: actions/upload-artifact@v3
        with:
          name: operator-machine-charm
          path: ./*.charm
          if-no-files-found: error
