name: ReleaseCharm

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: |
          The tag to build from. Release candidate tags are normally built from
          staging and production ready releases from master.

run-name: Release charm - operator-machine from tag ${{ inputs.tag }} by @${{ github.actor }}

jobs:
# Upload workflows for new charms.
# The action will build and release the charm
  upload-livepatch-operator-machine:
    runs-on: ubuntu-20.04
    env:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.4.0
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "ops1.x/edge"
          charm-path: "./"
          tag-prefix: "machine"
