name: Run integration tests

on:
  pull_request:

jobs:
  integration_tests:
    name: integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v4
    - run: sudo snap install charmcraft --channel=2.x/stable --classic
    - run: sudo snap install juju --channel=3.3/stable
    - uses: charmed-kubernetes/actions-operator@main 
      with: 
        juju-channel: 3.3/stable 
        provider: lxd
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run the integration tests
      run: tox -e integration
