name: Promote Charm

on:
  workflow_dispatch:
    inputs:
        origin-channel:
            type: choice
            description: 'Origin Channel'
            options:
            - latest/edge
            - latest/beta
            - latest/candidate
        destination-channel:
            type: choice
            description: 'Destination Channel'
            options:
            - latest/beta
            - latest/candidate
            - latest/stable
    secrets:
        CHARMHUB_TOKEN:
            required: true

jobs:
  promote:
    name: Promote Charm
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@8892eb826818585b397295e40276ddd0c5d3d459
    with:
      origin-channel: ${{ github.event.inputs.origin-channel }}
      destination-channel: ${{ github.event.inputs.destination-channel }}
    secrets: inherit
