name: Promote Bundle

on:
  workflow_dispatch:
    inputs:
      destination-channel:
        type: choice
        description: 'Destination Channel'
        options:
        - machine/beta
        - machine/candidate
        - machine/stable

jobs:
  promote:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # There is no action to promote a bundle so we use the upload action
      - name: Upload Bundle
        uses: canonical/charming-actions/upload-bundle@main
        with:
            credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
            tag-prefix: "bundle"
            bundle-path: ./bundle
            github-token: "${{ secrets.GITHUB_TOKEN }}"
            channel: ${{ github.event.inputs.destination-channel }}

