name: Publish to edge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    secrets: inherit
    with:
      channel: ops1.x/edge
