name: Tests

on:
  pull_request:

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@cc6be7e6ae364e738e6d46205f7df45774dfa767
    secrets: inherit
    with:
      self-hosted-runner: false
